baseURL: "https://alert-runbooks.kubesphere.io"
title: "WhizardTelemetry Alerting | Builtin Rules Runbooks"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

theme: book

params:
  BookRepo: "https://github.com/kubesphere/alert-runbooks"
  BookTheme: 'light'
  BookLogo: 'favicon.svg'
  BookSection: "runbooks"

languages:
  en:
    languageName: English
    contentDir: content
    title: WhizardTelemetry Alerting | Builtin Rules Runbooks
  zh:
    languageName: Chinese
    contentDir: content.zh
    title: WhizardTelemetry 告警 | 内置规则参考

markup:
  goldmark:
    renderer:
      # Allows rendering HTML tags. This would only be truly "unsafe" if we were accepting untrusted user input and rendering it, which we aren't.
      unsafe: true